# Generated by Django 2.2.12 on 2020-06-04 06:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Layer Name')),
                ('tool_tip_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('geo_point_field', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude_field', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude_field', models.CharField(blank=True, max_length=100, null=True)),
                ('data_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Field from the Table')),
                ('boundary_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Boundary Field')),
                ('layer_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('layer_type', models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon')], max_length=50)),
                ('aggregation_criteria', models.CharField(blank=True, choices=[('sum', 'Sum')], max_length=50, null=True)),
                ('create_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_last_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.Layer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Table', verbose_name='Linked Table')),
            ],
        ),
    ]
