# Generated by Django 2.2.12 on 2020-06-07 04:25

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0003_auto_20200606_1131'),
        ('maps', '0002_auto_20200606_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 25, 37, 139302, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='HistoricalMapLayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('layer_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Layer Name')),
                ('tool_tip_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None)),
                ('geo_point_field', models.CharField(blank=True, max_length=100)),
                ('latitude_field', models.CharField(blank=True, max_length=100)),
                ('longitude_field', models.CharField(blank=True, max_length=100)),
                ('value_field', models.CharField(blank=True, max_length=100, verbose_name='Value Field from the Table')),
                ('admin_boundary_field', models.CharField(blank=True, max_length=100)),
                ('layer_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None)),
                ('layer_type', models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon')], max_length=50)),
                ('aggregation_criteria', models.CharField(blank=True, choices=[('sum', 'Sum')], max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 25, 37, 139302, tzinfo=utc))),
                ('modified_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maps.MapLayer')),
                ('table', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.Table', verbose_name='Linked Table')),
            ],
            options={
                'verbose_name': 'historical map layer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
