# Generated by Django 2.2.12 on 2020-06-18 06:39

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import maps.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalpasswordresettoken_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0003_auto_20200607_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaplayer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 6, 39, 55, 115243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 6, 39, 55, 115243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_layer_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalAdminBoundary',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('boundary_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('boundary_code', models.CharField(blank=True, max_length=36)),
                ('properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), null=True, size=None)),
                ('geojson_url', models.CharField(blank=True, max_length=256)),
                ('geojson_file', models.TextField(max_length=100, null=True)),
                ('boundary_type', models.CharField(choices=[('country', 'Country'), ('custom', 'Custom')], default='country', max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 6, 39, 55, 113257, tzinfo=utc))),
                ('modified_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Workspace')),
            ],
            options={
                'verbose_name': 'historical admin boundary',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('boundary_code', models.CharField(blank=True, max_length=36)),
                ('properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), null=True, size=None)),
                ('geojson_url', models.CharField(blank=True, max_length=256)),
                ('geojson_file', models.FileField(null=True, upload_to=maps.models.get_geo_json_file_path)),
                ('boundary_type', models.CharField(choices=[('country', 'Country'), ('custom', 'Custom')], default='country', max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 6, 39, 55, 113257, tzinfo=utc))),
                ('modified_date', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_boundary_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Workspace')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmaplayer',
            name='admin_boundary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maps.AdminBoundary', verbose_name='Linked Admin Boundary'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='admin_boundary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.AdminBoundary', verbose_name='Linked Admin Boundary'),
        ),
    ]
