# Generated by Django 2.2.12 on 2020-06-18 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20200618_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminboundary',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='historicaladminboundary',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='adminboundary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 7, 53, 53, 668074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaladminboundary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 7, 53, 53, 668074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalmaplayer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 7, 53, 53, 669805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 7, 53, 53, 669805, tzinfo=utc)),
        ),
    ]
