# Generated by Django 2.2.12 on 2020-06-05 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workspaceinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkspace',
            old_name='url',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='url',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='historicalworkspace',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='slug',
        ),
        migrations.AddField(
            model_name='historicalworkspace',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='display name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalworkspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='display_name',
            field=models.CharField(default='', max_length=200, verbose_name='display name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='historicalworkspace',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='HistoricalWorkspaceInvitation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('key', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Workspace')),
            ],
            options={
                'verbose_name': 'historical workspace invitation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserActivation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user activation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
