# Generated by Django 2.2.12 on 2020-06-07 04:25

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useractivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0003_auto_20200606_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 25, 37, 136330, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='HistoricalTable',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('table_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('csv', 'csv'), ('kobo', 'kobo'), ('surveycto', 'surveycto'), ('ona', 'ona')], max_length=20)),
                ('unique_column', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 25, 37, 136330, tzinfo=utc))),
                ('update_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Workspace')),
            ],
            options={
                'verbose_name': 'historical table',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
